### ISSUE TITLE
platform.openstack.region: Internal error: could not retrieve valid regions 

### ISSUE THREAD

**Issue by jmutai** [openshift/installer#1916]
# Version

```console
$ openshift-install version
/openshift-install unreleased-master-1199-g06474dd31b58a4e4299473d41a4ab85cd488ebfc
built from commit 06474dd31b58a4e4299473d41a4ab85cd488ebfc
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform:

openstack

# What happened?

When I run:

```
$ openshift-install create cluster --dir=installer/ --log-level debug
```
I get the error:

```
**FATAL** failed to fetch Kubeconfig Admin Client: failed to load asset "Install Config": invalid "install-config.yaml" file: platform.openstack.region: Internal error: could not retrieve valid regions 
```

I have the following inside `installer/install-config.yaml`

```
........
platform:
  openstack:
    cloud:            openstack
    region:           RegionOne
    externalNetwork:  public
    computeFlavor:    m1.xlarge
....................
```

My clouds.yml file looks like below - Downloaded from Openstack

```
clouds:
  openstack:
    auth:
      auth_url: http://openstackip:5000/v3
      username: "admin"
      password:  
      project_id: d16dda64b73945898eebbd5be9572612
      project_name: "admin"
      user_domain_name: "Default"
    region_name: "RegionOne"
    interface: "public"
    identity_api_version: 3
```

# What you expected to happen?

The cluster should be created.

# How to reproduce it (as minimally and precisely as possible)?

- Download clouds.yaml to current directory
- Eedit clouds.yaml and enter password into it
- Run:

```
openshift-install create cluster --dir installer/
```

**Comment by jichenjc** [comment]
even if the yaml file from openstack, is the yaml file ok to interact with openstack ? 
and maybe check what happened inside openstack as well?

**Comment by jmutai** [comment]
The yaml file is working fine. I think the issue is on validation.

Again I can't boot from rhcos image imported to glance, it says no bootable device, is this the expected behaviour?

**Comment by mandre** [comment]
Can you confirm that you're able to get the region with `openstack region list` using the given clouds.yaml?

**Comment by mandre** [comment]
Sorry, I didn't refresh the page before posting and didn't see the new comments. The validation is happening in https://github.com/openshift/installer/blob/8daaee2/pkg/types/openstack/validation/realvalidvaluesfetcher.go#L35-L62. I do not see anything obviously wrong there. It would be helpful if you try to print the error returned by GetRegionNames() at https://github.com/openshift/installer/blob/8daaee2/pkg/types/openstack/validation/platform.go#L21-L22.

We certainly do not expect a `no bootable device` error with the rhcos image. See if my comment in https://github.com/openshift/installer/issues/1924 helps.

**Comment by jmutai** [comment]
Thanks for the response.

Btw are you using OpenStack in your test environment?

**Comment by mandre** [comment]
Any updates on this issue? We believe it should be fixed, could you try again?

**Comment by gtema** [comment]
the issue still exists for me. 
`openstack region list` works with the specially prepared clouds.yaml

**Comment by vklohiya** [comment]
Any update ?? I am also facing the same error:
```
FATAL failed to fetch Install Config: failed to load asset "Install Config": invalid "install-config.yaml" file: [platform.openstack.externalNetwork: Internal error: could not retrieve valid networks, platform.openstack.computeFlavor: Internal error: could not retrieve valid flavors, platform.openstack.trunkSupport: Internal error: could not retrieve networking extension aliases, platform.openstack.octaviaSupport: Internal error: could not retrieve service catalog]
```

**Comment by mandre** [comment]
@gtema, @vklohiya could you post the structure of your `clouds.yaml` file to help us debug the issue?

**Comment by mandre** [comment]
Also, any chance you folks are deploying on OpenStack with SSL terminated endpoint using self-signed certificates?

**Comment by vklohiya** [comment]
> Also, any chance you folks are deploying on OpenStack with SSL terminated endpoint using self-signed certificates?

@mandre , I am using the internal ca self-signed certificate in my clouds.yml

**Comment by vklohiya** [comment]
> @gtema, @vklohiya could you post the structure of your `clouds.yaml` file to help us debug the issue?

Here is my clouds.yaml:
```
clouds:
  openstack:
    auth:
      auth_url: https://xyz.com:5000/v3
      username: "vk123"
      project_id: "abc"
      project_name: "cc"
      user_domain_name: "olympus"
      password: "xxxx"
#    verify: False
    cacert: /home/centos/oscp43/f5-bundle.crt
    region_name: "RegionOne"
    interface: "public"
    identity_api_version: 3
```

**Comment by mandre** [comment]
> > Also, any chance you folks are deploying on OpenStack with SSL terminated endpoint using self-signed certificates?
> 
> @mandre , I am using the internal ca self-signed certificate in my clouds.yml

Perfect, this is what I was suspecting. You need to add your CA cert to the system trusts.

```
sudo cp /home/centos/oscp43/f5-bundle.crt /etc/pki/ca-trust/source/anchors/
sudo update-ca-trust extract
```

See https://github.com/openshift/installer/blob/8c55eae/docs/user/openstack/README.md#self-signed-openstack-ca-certificates and https://bugzilla.redhat.com/show_bug.cgi?id=1786314

**Comment by vklohiya** [comment]
> > > Also, any chance you folks are deploying on OpenStack with SSL terminated endpoint using self-signed certificates?
> > 
> > 
> > @mandre , I am using the internal ca self-signed certificate in my clouds.yml
> 
> Perfect, this is what I was suspecting. You need to add your CA cert to the system trusts.
> 
> ```
> sudo cp /home/centos/oscp43/f5-bundle.crt /etc/pki/ca-trust/source/anchors/
> sudo update-ca-trust extract
> ```
> 
> See https://github.com/openshift/installer/blob/8c55eae/docs/user/openstack/README.md#self-signed-openstack-ca-certificates and https://bugzilla.redhat.com/show_bug.cgi?id=1786314

Thanks @mandre , It worked for me.
