### ISSUE TITLE
resolv-prepender does not get proxy config from machine-config on first boot

### ISSUE THREAD

**Issue by EagleIJoe** [openshift/installer#4137]
# Version

```console
$ openshift-install version
openshift-install 4.5.0-0.okd-2020-08-12-020541
built from commit 699277bb61706731d687b9e40700ebf4630b0851
release image quay.io/openshift/okd@sha256:6974c414be62aee4fde24fe47ccfff97c2854ddc37eb196f3f3bcda2fdec17b4
```

# Platform:
ovirt

IPI

# What happened?
The master node boots and upon bringing up the network and running the resolv-prepender, the podman command fails for the first boot with machine-config, as the proxy environment has not been setup.

Podman tries to connect directly to the source IP, which is refused.

```console
Sep 03 13:50:39 cluster-l68gd-master-0 nm-dispatcher[855]: Trying to pull quay.io/openshift/okd-content@sha256:54ea8cd9dba05afa87faebf283fea8dd64c7678b82840b8b7037cc9bda0acdfd...
Sep 03 13:50:39 cluster-l68gd-master-0 nm-dispatcher[855]:   Get "https://quay.io/v2/": dial tcp 54.210.241.179:443: connect: connection refused
Sep 03 13:50:39 cluster-l68gd-master-0 nm-dispatcher[855]: Error: unable to pull quay.io/openshift/okd-content@sha256:54ea8cd9dba05afa87faebf283fea8dd64c7678b82840b8b7037cc9bda0acdfd: unable to pull image: Error initializing source docker://quay.io/openshift/okd-content@sha256:54ea8cd9dba05afa87faebf283fea8dd64c7678b82840b8b7037cc9bda0acdfd: error pinging docker registry quay.io: Get "https://quay.io/v2/": dial tcp 54.210.241.179:443: connect: connection refused
Sep 03 13:50:39 cluster-l68gd-master-0 nm-dispatcher[762]: req:4 'up' [ens3], "/etc/NetworkManager/dispatcher.d/30-resolv-prepender": complete: failed with Script '/etc/NetworkManager/dispatcher.d/30-resolv-prepender' exited with error status 125.
Sep 03 13:50:39 cluster-l68gd-master-0 NetworkManager[698]: <warn>  [1599141039.8880] dispatcher: (4) /etc/NetworkManager/dispatcher.d/30-resolv-prepender failed (failed): Script '/etc/NetworkManager/dispatcher.d/30-resolv-prepender' exited with error status 125.
```

This results in the resolv.conf not getting patched with local ip address, which in turn causes the further process to stall.

# What you expected to happen?
The master node patches the resolv.conf after coming up with its macine-config.

# How to reproduce it (as minimally and precisely as possible)?
1. add proxy section to install-config.yaml

```console
$ openshift-install with install-config.yaml
```

# Anything else we need to know?
I have the additionalTrustBundle set as well as proxy does MITM. Maybe this is could be a reason for the failure as well.

A reboot of the machine solves the problem, as it appears to have the proxy config properly written by that point.

# References

**Comment by mandre** [comment]
Hi, this should have been fixed with https://github.com/openshift/machine-config-operator/pull/1985. Could you try again with a newer build?

**Comment by EagleIJoe** [comment]
Hi @mandre,

this still happens with:

> ./openshift-install 4.5.0-0.okd-2020-09-04-180756
> built from commit 63200c80c431b8dbaa06c0cc13282d819bd7e5f8
> release image quay.io/openshift/okd@sha256:eeb7ba7c0ca5749f2e27e0951da70263658301f5bfa4fdd86524d73bfdeb7cac

This is the newest GA build of OKD.

**Comment by mandre** [comment]
Looks like fcos-4.5 branch of machine-config-operator wasn't sync'ed in a long time. We'll need openshift/machine-config-operator#1985 in https://github.com/openshift/machine-config-operator/tree/fcos-4.5.
@vrutkovs is that something you can help with?

**Comment by vrutkovs** [comment]
We're using `fcos` branch, `fcos-4.5` would be removed

**Comment by vrutkovs** [comment]
Please don't file OKD issues in this repo, use https://github.com/openshift/okd.

This commit would be cherry-picked in the next round of rebase, approx. this weekend.

/close
