### ISSUE TITLE
bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c is often down, please reference another URL

### ISSUE THREAD

**Issue by ElCoyote27** [openshift/installer#4162]
Hi,
Trying to rebuild the openshift installed with libvirt support, we get this:

```
[gnunn@lab-server installer]$ go get
go: github.com/openshift/library-go@v0.0.0-20200324092245-db2a8546af81 requires
        bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
```

Is there another alternate URL which could be provided either on github or here? 
this URL is referenced in the go.sum file from the openshift installer.
Thank you,
Vincent

**Comment by schmaustech** [comment]
This also shows up when using the machine-api-operator:

``+ go generate ./data
go: github.com/openshift/machine-api-operator@v0.2.1-0.20200429102619-d36974451290 requires
	github.com/openshift/library-go@v0.0.0-20200324092245-db2a8546af81 requires
	bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
``

**Comment by cfergeau** [comment]
This was an issue in library-go, not in the installer, and has been fixed by https://github.com/openshift/library-go/pull/776/files

**Comment by marshallford** [comment]
I'm still seeing this error in branch `release-4.5`, in master I'm seeing another issue that I may open a separate issue for:

```
❯ hack/build.sh
+ minimum_go_version=1.14
++ go version
++ cut -d ' ' -f 3
+ current_go_version=go1.14.9
++ version 1.14.9
++ IFS=.
++ printf '%03d%03d%03d\n' 1 14 9
++ unset IFS
++ version 1.14
++ IFS=.
++ printf '%03d%03d%03d\n' 1 14
++ unset IFS
+ '[' 001014009 -lt 001014000 ']'
+ MODE=release
++ git rev-parse --verify 'HEAD^{commit}'
+ GIT_COMMIT=7fd66477e7aa23d7a7ed5d0b8973e74cdae819ea
++ git describe --always --abbrev=40 --dirty
+ GIT_TAG=unreleased-master-3789-g7fd66477e7aa23d7a7ed5d0b8973e74cdae819ea
+ GOFLAGS=-mod=vendor
+ LDFLAGS=' -X github.com/openshift/installer/pkg/version.Raw=unreleased-master-3789-g7fd66477e7aa23d7a7ed5d0b8973e74cdae819ea -X github.com/openshift/installer/pkg/version.Commit=7fd66477e7aa23d7a7ed5d0b8973e74cdae819ea'
+ TAGS=
+ OUTPUT=bin/openshift-install
+ export CGO_ENABLED=0
+ CGO_ENABLED=0
+ case "${MODE}" in
+ LDFLAGS=' -X github.com/openshift/installer/pkg/version.Raw=unreleased-master-3789-g7fd66477e7aa23d7a7ed5d0b8973e74cdae819ea -X github.com/openshift/installer/pkg/version.Commit=7fd66477e7aa23d7a7ed5d0b8973e74cdae819ea -s -w'
+ TAGS=' release'
+ test '' '!=' y
+ go generate ./data
../vendor/github.com/shurcooL/vfsgen/generator.go:4:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/bytes
../vendor/github.com/shurcooL/vfsgen/generator.go:5:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/compress/gzip
../vendor/github.com/shurcooL/vfsgen/generator.go:6:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/errors
../vendor/github.com/shurcooL/vfsgen/generator.go:7:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/fmt
unpack.go:4:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/io
../vendor/github.com/shurcooL/httpfs/vfsutil/vfsutil.go:5:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/io/ioutil
assets_generate.go:6:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/log
assets.go:7:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/net/http
assets.go:8:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/os
unpack.go:6:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/path
unpack.go:7:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/path/filepath
package main
	imports runtime: cannot find package
../vendor/github.com/shurcooL/httpfs/vfsutil/walk.go:9:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/sort
../vendor/github.com/shurcooL/vfsgen/generator.go:14:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/strconv
../vendor/github.com/shurcooL/vfsgen/options.go:5:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/strings
../vendor/github.com/shurcooL/vfsgen/generator.go:15:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/text/template
../vendor/github.com/shurcooL/vfsgen/generator.go:16:2: cannot find package "." in:
	/home/mford/okd4/installer/vendor/time
data/assets.go:2: running "go": exit status 1
```

**Comment by cfergeau** [comment]
Ah, seems like the installer release-4.5 `go.mod` file was not updated after this was fixed in `library-go` :-/

**Comment by ElCoyote27** [comment]
Re-opening for release-4.5.
OCP 4.5 is still widely used (and is the only version currently supported by 'OpenStack Service Telemetry Framework' so please fix it for OCP 4.5 as well.

**Comment by staebler** [comment]
This will not be fixed in 4.5. It involves updating quite a few dependencies, which carries too much risk to backport, unfortunately.

/close
